#!/bin/bash
# ============================================================
# BOSATEK SENTINEL V2 — modules/ai_brain.sh
# Background AI loop: tails summary.log → updates checklist.md
# ============================================================

# ai_brain_loop <ROOM_DIR>
# Runs continuously in the background, detecting new entries
# appended to summary.log and asking the local Ollama model to
# update checklist.md with prioritised attack vectors.
ai_brain_loop() {
    local ROOM_DIR="${1:-.}"
    local SUMMARY_LOG="$ROOM_DIR/logs/summary.log"
    local CHECKLIST="$ROOM_DIR/checklist.md"
    local STATE_FILE="$ROOM_DIR/logs/.ai_brain_cursor"
    local POLL_INTERVAL=10

    echo "[AI-Brain] Starting background loop..."
    echo "[AI-Brain] Watching : $SUMMARY_LOG"
    echo "[AI-Brain] Checklist: $CHECKLIST"
    echo ""

    # Initialise checklist if missing
    if [[ ! -f "$CHECKLIST" ]]; then
        mkdir -p "$ROOM_DIR"
        cat > "$CHECKLIST" <<'INIT'
# Bosatek Sentinel — Attack Checklist

> Auto-generated by AI-Brain. Last updated: pending first scan.

## Pending Review
- [ ] Awaiting scan results...
INIT
    fi

    # Track byte offset so we only process NEW lines
    local LAST_SIZE=0
    if [[ -f "$STATE_FILE" ]]; then
        LAST_SIZE=$(cat "$STATE_FILE" 2>/dev/null || echo 0)
    fi

    while true; do
        if [[ ! -f "$SUMMARY_LOG" ]]; then
            sleep "$POLL_INTERVAL"
            continue
        fi

        local CURRENT_SIZE
        CURRENT_SIZE=$(wc -c < "$SUMMARY_LOG" 2>/dev/null || echo 0)

        if [[ "$CURRENT_SIZE" -gt "$LAST_SIZE" ]]; then
            # Read only the new bytes appended since last check
            local NEW_CONTENT
            NEW_CONTENT=$(tail -c "+$((LAST_SIZE + 1))" "$SUMMARY_LOG" 2>/dev/null)

            if [[ -n "$NEW_CONTENT" ]]; then
                echo "[AI-Brain] New data detected ($(( CURRENT_SIZE - LAST_SIZE )) bytes). Querying AI..."

                local AI_RESPONSE
                AI_RESPONSE=$(_query_ai "$NEW_CONTENT" 2>/dev/null)

                if [[ -n "$AI_RESPONSE" ]]; then
                    _update_checklist "$CHECKLIST" "$AI_RESPONSE"
                    echo "[AI-Brain] Checklist updated: $(date)"
                else
                    echo "[AI-Brain] AI returned empty response — skipping update."
                fi
            fi

            LAST_SIZE="$CURRENT_SIZE"
            echo "$LAST_SIZE" > "$STATE_FILE"
        fi

        sleep "$POLL_INTERVAL"
    done
}

# _query_ai <RAW_SCAN_DATA>
# Sends new scan data to the local Ollama model and returns a
# markdown bullet list of attack vectors.
_query_ai() {
    local SCAN_DATA="$1"

    # Truncate to last 4000 chars to stay within context window
    local TRUNCATED
    TRUNCATED=$(echo "$SCAN_DATA" | tail -c 4000)

    # Prompt instructs the model to output only checklist items
    local PROMPT
    PROMPT=$(cat <<PROMPT
New scan results appended below. Reply ONLY with a markdown checklist of prioritised attack vectors. Format each line as: - [ ] <vector>. No preamble, no explanation.

$TRUNCATED
PROMPT
)

    if command -v ollama &>/dev/null; then
        echo "$PROMPT" | ollama run bosatek-sentinel 2>/dev/null
    else
        echo "- [ ] ollama not available — manual review required"
    fi
}

# _update_checklist <CHECKLIST_PATH> <AI_RESPONSE>
# Appends a timestamped AI response block to checklist.md
_update_checklist() {
    local CHECKLIST="$1"
    local AI_RESPONSE="$2"
    local TIMESTAMP
    TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")

    {
        echo ""
        echo "## AI Update — $TIMESTAMP"
        echo ""
        echo "$AI_RESPONSE"
    } >> "$CHECKLIST"
}
